### ISSUE TITLE
DiscordChatExporter: extract components?

### ISSUE THREAD

**Issue by TheTechRobo** [TheTechRobo/discord-urls-extractor#30]
It's not clear to me whether they're supported; https://github.com/Tyrrrz/DiscordChatExporter/issues/642 implies that they are downloaded, just not shown in the HTML. Does that mean they are shown in the JSON? I'll have to investigate this.

**Comment by sazio** [comment]
Any news on this @TheTechRobo? :)

**Comment by TheTechRobo** [comment]
@sazio Thanks for the reminder! In a few hours I'll find a server that has components and scrape it. That way I'll be pretty sure as to whether or not they are saved.

**Comment by sazio** [comment]
@TheTechRobo I tried quickly and it doesn't seem to scrape them, but let me know what you find! Thank you very much 🙌

**Comment by TheTechRobo** [comment]
Sorry for the late response-

Doesn't look like components are saved. Tested on RoboTop's official Discord - I can't find any reference to the two buttons in the JSON.

![image](https://user-images.githubusercontent.com/52163910/235307622-446f210f-2a04-4460-ab40-b4ad0818f52f.png)

Closing as non-actionable. If DCE adds support for this in the future, let me know.

**Comment by sazio** [comment]
Thanks for double checking, such a pity !
